project:
  type: website
  output-dir: docs

website:
  title: "Yoonhee Choi"
  description: "Climate Policy, Inequality, and Vulnerable Populations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/YoonheeChoi0613
      - icon: envelope
        href: mailto:Yoonhee.Choi@UTDallas.edu

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true